//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryEnitiyFrameworkWEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContraEntry
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string FromCashAccount { get; set; }
        public string FromBankAccount { get; set; }
        public string ToCashAccount { get; set; }
        public string ToBankAccount { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Note { get; set; }
    }
}
