//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryEnitiyFrameworkWEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Item_Invoice
    {
        public int Id { get; set; }
        public Nullable<int> Item_Id { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Item Item { get; set; }
    }
}
