//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryEnitiyFrameworkWEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewStockItem
    {
        public int NewStocks_Id { get; set; }
        public int NewStocks_SupplierName { get; set; }
        public int NewStocks_Date { get; set; }
        public int NewStocks_City { get; set; }
        public int NewStocks_Note { get; set; }
        public int NewStocks_TotalQuantity { get; set; }
        public int Items_Id { get; set; }
    }
}
