//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryEnitiyFrameworkWEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuantityAndPrice
    {
        public int Id { get; set; }
        public Nullable<int> Item_Id { get; set; }
        public Nullable<int> CostPrice { get; set; }
        public Nullable<int> SalsePrice { get; set; }
        public Nullable<int> ProfitPercentage { get; set; }
        public Nullable<int> BatchNumber { get; set; }
        public Nullable<System.DateTime> ManuFacturingDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> Unit_Id { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Unit Unit { get; set; }
    }
}
