//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryEnitiyFrameworkWEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Supplier_PurcchaseIvoice_SupplierPayment
    {
        public int Id { get; set; }
        public string PaymentType { get; set; }
        public string ChequeNumber { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<double> PaidAmount { get; set; }
        public Nullable<double> BalanceAmount { get; set; }
        public Nullable<System.DateTime> DepositeDate { get; set; }
        public string DepositeTo { get; set; }
        public string BankName { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Name { get; set; }
        public int PurchaseInvoiceID { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<double> TotalTaxAmount { get; set; }
        public Nullable<double> ShippingCost { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> RoundOff { get; set; }
        public Nullable<double> NetAmount { get; set; }
        public int TransactionId { get; set; }
    }
}
