//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureInventoryEntityFrameworkWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country_State_City_View
    {
        public int Country_ID { get; set; }
        public string CountryName { get; set; }
        public int State_ID { get; set; }
        public string StateName { get; set; }
        public int City_ID { get; set; }
        public string City { get; set; }
    }
}
