//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureInventoryEntityFrameworkWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mInventoryEntities : DbContext
    {
        public mInventoryEntities()
            : base("name=mInventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BankAccount> BankAccounts { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<BusinessDetail> BusinessDetails { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<ContraEntry> ContraEntries { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CustomerPayment> CustomerPayments { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Expens> Expenses { get; set; }
        public virtual DbSet<ForgetPassword> ForgetPasswords { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<LogIn> LogIns { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<NewStockItem> NewStockItems { get; set; }
        public virtual DbSet<NewStock> NewStocks { get; set; }
        public virtual DbSet<NewUnit> NewUnits { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Organisation> Organisations { get; set; }
        public virtual DbSet<PartyPaymnet> PartyPaymnets { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PaymentSupplier> PaymentSuppliers { get; set; }
        public virtual DbSet<Percentage> Percentages { get; set; }
        public virtual DbSet<PurchaseInvoice> PurchaseInvoices { get; set; }
        public virtual DbSet<QuantityAndPrice> QuantityAndPrices { get; set; }
        public virtual DbSet<RoleOfUser> RoleOfUsers { get; set; }
        public virtual DbSet<SalesInvoice> SalesInvoices { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<StockInHand> StockInHands { get; set; }
        public virtual DbSet<SubMenu> SubMenus { get; set; }
        public virtual DbSet<SupplierPayment> SupplierPayments { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Tax> Taxes { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Country_State_City_View> Country_State_City_View { get; set; }
        public virtual DbSet<Customer_View> Customer_View { get; set; }
        public virtual DbSet<ServicesView> ServicesViews { get; set; }
        public virtual DbSet<Supplier_View> Supplier_View { get; set; }
        public virtual DbSet<View_Categories> View_Categories { get; set; }
        public virtual DbSet<View_Companies> View_Companies { get; set; }
        public virtual DbSet<View_Country> View_Country { get; set; }
        public virtual DbSet<View_Customer_Payment_SalesInvoice> View_Customer_Payment_SalesInvoice { get; set; }
        public virtual DbSet<View_Item> View_Item { get; set; }
        public virtual DbSet<View_New_Units> View_New_Units { get; set; }
        public virtual DbSet<View_Role> View_Role { get; set; }
        public virtual DbSet<View_Unit> View_Unit { get; set; }
        public virtual DbSet<View_Users> View_Users { get; set; }
        public virtual DbSet<View_Users_Role> View_Users_Role { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
