//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureInventoryEntityFrameworkWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int Id { get; set; }
        public string ServiceName { get; set; }
        public Nullable<int> SalesPrice { get; set; }
        public Nullable<int> PurchasePrice { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public Nullable<int> PurchaseTax_ID { get; set; }
        public Nullable<int> SalesTax_ID { get; set; }
        public Nullable<bool> AllowSales { get; set; }
        public Nullable<bool> AllowPurchase { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
