//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureInventoryEntityFrameworkWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_New_Units
    {
        public int Id { get; set; }
        public string FromQuantity { get; set; }
        public Nullable<int> FromUnit { get; set; }
        public Nullable<int> Name { get; set; }
        public string ToQuantity { get; set; }
        public Nullable<int> ToUnit { get; set; }
        public Nullable<int> ToUnitName { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
